version: "3.8"
services:
  firestore:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Emulator UI
      - "8080:8080" # Firestore port
    volumes:
      - ./firebase-data:/home/firebase/.firebase
    command: >
      bash -c "gcloud config set project splitin-firebase &&
               gcloud emulators firestore start --host-port=0.0.0.0:8080"
