from flask_restful import reqparse
from werkzeug.datastructures import FileStorage 

post_parser = reqparse.RequestParser()
post_parser.add_argument('name', type=str, location=['form'], required=True, help="str `name` is required")
post_parser.add_argument('email', type=str, location=['form'], required=True, help="str `email` is required")
post_parser.add_argument('password', type=str, location=['form'], required=True, help="str `password` is required")
post_parser.add_argument('student_id', type=str, location=['form'], required=True, help="str `student_id` is required")
post_parser.add_argument('phone_number', type=str, location=['form'], required=True, help="str `phone_number` is required")
post_parser.add_argument('type', choices=('CLIENT', 'CUSTOMER'), type=str, location=['form'], required=True, help="str `type (CLIENT or CUSTOMER)` is required")
post_parser.add_argument('gender', choices=('MALE', 'FEMALE'), type=str, location=['form'], required=True, help="str `gender (MALE or FEMALE)` is required")
post_parser.add_argument('interest', type=str, location=['form'], required=False)
post_parser.add_argument('bank_account', type=str, location=['form'], required=False)
post_parser.add_argument('bank_name', type=str, location=['form'], required=False)
post_parser.add_argument('ktm', type=FileStorage, location=['files'], required=False)

patch_parser = reqparse.RequestParser()
patch_parser.add_argument('name', type=str, location=['form'], required=False, help="str `name` is required")
patch_parser.add_argument('email', type=str, location=['form'], required=False, help="str `email` is required")
patch_parser.add_argument('student_id', type=str, location=['form'], required=False, help="str `student_id` is required")
patch_parser.add_argument('phone_number', type=str, location=['form'], required=False, help="str `phone_number` is required")
patch_parser.add_argument('gender', choices=('MALE', 'FEMALE'), type=str, location=['form'], required=False, help="str `gender (MALE or FEMALE)` is required")
patch_parser.add_argument('interest', type=str, location=['form'], required=False)
patch_parser.add_argument('bank_account', type=str, location=['form'], required=False)
patch_parser.add_argument('bank_name', type=str, location=['form'], required=False)
patch_parser.add_argument('ktm', type=FileStorage, location=['files'], required=False)